#!/usr/bin/env python3
"""Residual add: OUT = X + RES  (fp32, rows=128 tokens, cols=512 hidden). TinyLlama block has
two of these (after attention, after FFN). Element-wise; exact fp32 add."""
import numpy as np
R, Cc = 128, 512
rng = np.random.default_rng(28)
X   = rng.standard_normal((R, Cc), dtype=np.float32)
RES = rng.standard_normal((R, Cc), dtype=np.float32)
gold = (X + RES).astype(np.float32)
def emit(f, name, arr):
    flat = arr.flatten()
    f.write(f"__global float {name}[{flat.size}] = {{\n")
    f.write(",\n".join(f"{x:.9e}f" for x in flat)); f.write("\n};\n")
with open("data", "w") as f:
    f.write("// generated by gen_data.py - do not edit\n")
    f.write(f"#define VERIFY_COUNT {R*Cc}\n")
    f.write(f"static const uint32_t ROWS = {R};\nstatic const uint32_t COLS = {Cc};\n")
    emit(f, "x_raw", X); emit(f, "res_raw", RES)
    emit(f, "out_raw", np.zeros((R, Cc), np.float32)); emit(f, "gold_raw", gold)
    f.write("__global float tls_guard[1024] = {0};\n")
print(f"wrote data: ResAdd {R}x{Cc}")
