#!/usr/bin/env python3
"""Gemma-2 scaled embedding gather: OUT[t,:] = TABLE[ids[t],:] * sqrt(D)
(fp32, T=16 tokens, D=2304 = real Gemma-2-2b hidden_size).

Confirmed from HF Gemma2TextScaledWordEmbedding: embed_scale = hidden_size**0.5.
sqrt(2304) = 48.0 exactly, so the scale is representable in bf16/fp32 with no rounding.
The vocab is 256000 in the real model; correctness of a gather+scale is independent of V,
so we use a small representative table (V=96) and random token ids in [0, V).
"""
import numpy as np
V, D, T = 96, 2304, 16
SCALE = np.float32(np.sqrt(D))   # 48.0 exactly
assert SCALE == np.float32(48.0)
rng = np.random.default_rng(41)
TABLE = rng.standard_normal((V, D), dtype=np.float32)
ids = rng.integers(0, V, size=T).astype(np.uint32)
gold = (TABLE[ids].astype(np.float64) * SCALE).astype(np.float32)

def emit_f(f, name, arr):
    flat = arr.flatten()
    f.write(f"__global float {name}[{flat.size}] = {{\n")
    f.write(",\n".join(f"{x:.9e}f" for x in flat)); f.write("\n};\n")
def emit_u(f, name, arr):
    flat = arr.flatten()
    f.write(f"__global uint32_t {name}[{flat.size}] = {{\n")
    f.write(",".join(str(int(x)) for x in flat)); f.write("\n};\n")
with open("data", "w") as f:
    f.write("// generated by gen_data.py - do not edit\n")
    f.write(f"#define VERIFY_COUNT {T*D}\n")
    f.write(f"static const uint32_t TT = {T};\nstatic const uint32_t DD = {D};\n")
    emit_f(f, "table_raw", TABLE); emit_u(f, "ids_raw", ids)
    emit_f(f, "out_raw", np.zeros((T, D), np.float32)); emit_f(f, "gold_raw", gold)
    f.write("__global float tls_guard[1024] = {0};\n")
print(f"wrote data: Gemma scaled embed gather T={T} D={D} scale={float(SCALE)}")
