#!/usr/bin/env python3
"""GELU tile: C[m,n] = x * sigmoid(1.702*x) (fp32 sigmoid-approx, rows=64, cols=512).

Real op: smolvla/pi05 MLP gelu (1x1024x3072), tiled to a 64x512 elementwise block. Exact-erf
gelu can't be FP-matched without an erf intrinsic, so we use the sigmoid approximation, computed
in the golden with the SAME mu_exp polynomial the kernel uses.
"""
import numpy as np

M, N = 64, 512
rng = np.random.default_rng(99)
A = rng.standard_normal((M, N), dtype=np.float32)


def mu_exp(x):
    x = np.float32(x)
    log2e = np.float32(1.4426950408889634)
    ln2 = np.float32(0.6931471805599453)
    t = x * log2e
    k = np.where(t >= 0, t + np.float32(0.5), t - np.float32(0.5)).astype(np.int32)
    r = x - k.astype(np.float32) * ln2
    p = np.float32(1.0) + r * (np.float32(1.0) + r * (np.float32(0.5) + r * (
        np.float32(0.16666667) + r * (np.float32(0.041666668) + r * np.float32(0.008333334)))))
    return (p * np.exp2(k.astype(np.float32))).astype(np.float32)


z = (np.float32(1.702) * A).astype(np.float32)
sig = (np.float32(1.0) / (np.float32(1.0) + mu_exp((-z).astype(np.float32)))).astype(np.float32)
gold = (A * sig).astype(np.float32)


def emit(f, name, arr):
    flat = arr.flatten()
    f.write(f"__global float {name}[{flat.size}] = {{\n")
    f.write(",\n".join(f"{x:.9e}f" for x in flat))
    f.write("\n};\n")


with open("data", "w") as f:
    f.write("// generated by gen_data.py - do not edit\n")
    f.write(f"#define VERIFY_COUNT {M * N}\n")
    f.write(f"static const uint32_t M = {M};\n")
    f.write(f"static const uint32_t N = {N};\n")
    emit(f, "A_raw", A)
    emit(f, "C_raw", np.zeros((M, N), dtype=np.float32))
    emit(f, "gold_raw", gold)
    f.write("__global float tls_guard[1024] = {0};\n")
print(f"wrote data: gelu {M}x{N}")
