#!/usr/bin/env python3
"""smolvla-representative matmul tile: C[M,N]=A[M,K]@B[K,N], fp32.
Shape M=64,N=64,K=256 mirrors openvla 20x128 @ 128x512 (K=128, freq 7); full A,B staging fits SMEM (64KB).
(the 768 contraction depth — 12x deeper than the 64^3 stand-in — is where
on-chip staging / accumulation reuse actually pays off)."""
import numpy as np
M, N, K = 64, 64, 128
rng = np.random.default_rng(42)
A = rng.standard_normal((M, K), dtype=np.float32)
B = rng.standard_normal((K, N), dtype=np.float32)
gold = np.zeros((M, N), dtype=np.float32)
for k in range(K):
    gold += A[:, k:k+1] * B[k:k+1, :]
def emit(f,name,arr):
    flat=arr.flatten(); f.write(f"__global float {name}[{flat.size}] = {{\n")
    f.write(",\n".join(f"{x:.9e}f" for x in flat)); f.write("\n};\n")
with open("data","w") as f:
    f.write("// generated by gen_data.py - do not edit\n")
    f.write(f"#define VERIFY_COUNT {M*N}\n")
    f.write(f"static const uint32_t M = {M};\n")
    f.write(f"static const uint32_t N = {N};\n")
    f.write(f"static const uint32_t K = {K};\n")
    emit(f,"A_raw",A); emit(f,"B_raw",B)
    emit(f,"C_raw",np.zeros((M,N),dtype=np.float32)); emit(f,"gold_raw",gold)
    f.write("__global float tls_guard[1024] = {0};\n")
print(f"wrote data: M={M} N={N} K={K}")
