#!/usr/bin/env python3
"""SwiGLU activation tile: C[m,n] = silu(A[m,n]) * B[m,n], fp32 (m=64, n=512).

Real op: rdt FFN silu(x)*y, 2048-dim, tiled to 64x128.
silu(x) = x * sigmoid(x) computed with the same mu_exp polynomial as the harness.
"""
import numpy as np

Mr, Nc = 64, 128
rng = np.random.default_rng(21)
A = rng.standard_normal((Mr, Nc), dtype=np.float32)
B = rng.standard_normal((Mr, Nc), dtype=np.float32)

# Keep activations in a moderate range: limits mu_exp argument so the device's
# FMA-contracted polynomial stays within tolerance of the numpy reference, and
# avoids the k=round(t) tie boundary flipping exp scale by 2x.
A = np.tanh(A).astype(np.float32) * np.float32(1.8)
LOG2E = np.float32(1.4426950408889634)
for _ in range(50):
    t = -A * LOG2E
    near = np.abs(t - np.floor(t) - 0.5) < 1e-3
    if not near.any():
        break
    A = np.where(near, np.clip(rng.standard_normal(A.shape), -2, 2).astype(np.float32), A)


def mu_exp(x):
    x = np.float32(x)
    log2e = np.float32(1.4426950408889634)
    ln2 = np.float32(0.6931471805599453)
    t = x * log2e
    k = np.where(t >= 0, t + np.float32(0.5), t - np.float32(0.5)).astype(np.int32)
    r = x - k.astype(np.float32) * ln2
    p = np.float32(1.0) + r * (np.float32(1.0) + r * (np.float32(0.5) + r * (
        np.float32(0.16666667) + r * (np.float32(0.041666668) + r * np.float32(0.008333334)))))
    return (p * np.exp2(k.astype(np.float32))).astype(np.float32)


sig = (np.float32(1.0) / (np.float32(1.0) + mu_exp(-A))).astype(np.float32)
gold = (A * sig * B).astype(np.float32)


def emit(f, name, arr):
    flat = arr.flatten()
    f.write(f"__global float {name}[{flat.size}] = {{\n")
    f.write(",\n".join(f"{x:.9e}f" for x in flat))
    f.write("\n};\n")


with open("data", "w") as f:
    f.write("// generated by gen_data.py - do not edit\n")
    f.write(f"#define VERIFY_COUNT {Mr * Nc}\n")
    f.write(f"static const uint32_t M = {Mr};\n")
    f.write(f"static const uint32_t N = {Nc};\n")
    emit(f, "A_raw", A)
    emit(f, "B_raw", B)
    emit(f, "C_raw", np.zeros((Mr, Nc), dtype=np.float32))
    emit(f, "gold_raw", gold)
    f.write("__global float tls_guard[1024] = {0};\n")
print(f"wrote data: swiglu {Mr}x{Nc}")
