#!/usr/bin/env python3
"""Generate `data` header for muon matmul problem: C[M,N] = A[M,K] @ B[K,N], fp32.

Deterministic; golden computed in numpy float32 (IEEE).
"""
import numpy as np

M, N, K = 64, 64, 64
rng = np.random.default_rng(42)
A = rng.standard_normal((M, K), dtype=np.float32)
B = rng.standard_normal((K, N), dtype=np.float32)

# Sequential fp32 accumulation over k — matches a scalar device loop bit-for-bit
# (numpy matmul uses pairwise summation, which differs by many ULPs).
gold = np.zeros((M, N), dtype=np.float32)
for k in range(K):
    gold += A[:, k : k + 1] * B[k : k + 1, :]


def emit_array(f, name, arr):
    # 9 significant decimal digits round-trips binary32 exactly.
    flat = arr.flatten()
    f.write(f"__global float {name}[{flat.size}] = {{\n")
    f.write(",\n".join(f"{x:.9e}f" for x in flat))
    f.write("\n};\n")


with open("data", "w") as f:
    f.write("// generated by gen_data.py - do not edit\n")
    f.write(f"#define VERIFY_COUNT {M * N}\n")
    f.write(f"static const uint32_t M = {M};\n")
    f.write(f"static const uint32_t N = {N};\n")
    f.write(f"static const uint32_t K = {K};\n")
    emit_array(f, "A_raw", A)
    emit_array(f, "B_raw", B)
    emit_array(f, "C_raw", np.zeros((M, N), dtype=np.float32))
    emit_array(f, "gold_raw", gold)
    f.write("__global float tls_guard[1024] = {0};\n")
print(f"wrote data: M={M} N={N} K={K}")
