#!/usr/bin/env python3
"""Layer norm tile: OUT[r,:] = (IN[r,:]-mean)/sqrt(var+eps)*gamma+beta (fp32, rows=64, cols=768).

Real op: smolvla/openvla layer_norm over hidden=768 (1x1024x768). var is biased (ddof=0),
matching a device two-pass (mean, then sum of squared deviations / cols). eps=1e-5.
"""
import numpy as np

R, Cc = 64, 768
EPS = np.float32(1e-5)
rng = np.random.default_rng(88)
X = rng.standard_normal((R, Cc), dtype=np.float32)
gamma = (np.float32(1.0) + np.float32(0.1) * rng.standard_normal(Cc, dtype=np.float32)).astype(np.float32)
beta = (np.float32(0.1) * rng.standard_normal(Cc, dtype=np.float32)).astype(np.float32)

mean = X.mean(axis=1, keepdims=True).astype(np.float32)
var = (((X - mean) ** 2).mean(axis=1, keepdims=True)).astype(np.float32)  # biased, two-pass
inv = (np.float32(1.0) / np.sqrt(var + EPS)).astype(np.float32)
gold = (((X - mean) * inv) * gamma + beta).astype(np.float32)


def emit(f, name, arr):
    flat = arr.flatten()
    f.write(f"__global float {name}[{flat.size}] = {{\n")
    f.write(",\n".join(f"{x:.9e}f" for x in flat))
    f.write("\n};\n")


with open("data", "w") as f:
    f.write("// generated by gen_data.py - do not edit\n")
    f.write(f"#define VERIFY_COUNT {R * Cc}\n")
    f.write(f"static const uint32_t ROWS = {R};\n")
    f.write(f"static const uint32_t COLS = {Cc};\n")
    emit(f, "x_raw", X)
    emit(f, "gamma_raw", gamma)
    emit(f, "beta_raw", beta)
    emit(f, "out_raw", np.zeros((R, Cc), dtype=np.float32))
    emit(f, "gold_raw", gold)
    f.write("__global float tls_guard[1024] = {0};\n")
print(f"wrote data: layer_norm {R}x{Cc}")
