#!/usr/bin/env python3
"""Decode GEMV: out[n] = sum_k W[n,k]*x[k]  (fp32, N=512 outputs, K=512 hidden).

Autoregressive decode makes every projection a matrix-vector product (single token). Memory-bound:
one weight-row read per output. Golden = W @ x (fp64 accum, cast fp32). Matches a plain GEMV.
"""
import numpy as np
N, K = 64, 128
rng = np.random.default_rng(29)
W = rng.standard_normal((N, K), dtype=np.float32)
x = rng.standard_normal((K,), dtype=np.float32)
gold = (W.astype(np.float64) @ x.astype(np.float64)).astype(np.float32)
def emit(f, name, arr):
    flat = arr.flatten()
    f.write(f"__global float {name}[{flat.size}] = {{\n")
    f.write(",\n".join(f"{v:.9e}f" for v in flat)); f.write("\n};\n")
with open("data", "w") as f:
    f.write("// generated by gen_data.py - do not edit\n")
    f.write(f"#define VERIFY_COUNT {N}\n")
    f.write(f"static const uint32_t NN = {N};\nstatic const uint32_t KK = {K};\n")
    emit(f, "w_raw", W); emit(f, "x_raw", x)
    emit(f, "out_raw", np.zeros((N,), np.float32)); emit(f, "gold_raw", gold)
    f.write("__global float tls_guard[1024] = {0};\n")
print(f"wrote data: GEMV(small-RTL) N={N} K={K}")
