#!/usr/bin/env python3
"""Single-head attention: O = softmax(Q @ K^T / sqrt(d)) @ V (fp32, seq=64, head_dim=64).

Real op: rdt SDPA, 32 heads x 67 seq x 64 head_dim. Tile: one head, seq 64.
"""
import numpy as np

SEQ, D = 64, 64
rng = np.random.default_rng(13)
Q = rng.standard_normal((SEQ, D), dtype=np.float32)
K = rng.standard_normal((SEQ, D), dtype=np.float32)
V = rng.standard_normal((SEQ, D), dtype=np.float32)

def mu_exp(x):
    """fp32 polynomial exp identical to mu_exp() in the harness."""
    x = np.float32(x)
    log2e = np.float32(1.4426950408889634)
    ln2 = np.float32(0.6931471805599453)
    t = x * log2e
    k = np.where(t >= 0, t + np.float32(0.5), t - np.float32(0.5)).astype(np.int32)
    r = x - k.astype(np.float32) * ln2
    p = np.float32(1.0) + r * (np.float32(1.0) + r * (np.float32(0.5) + r * (
        np.float32(0.16666667) + r * (np.float32(0.041666668) + r * np.float32(0.008333334)))))
    return (p * np.exp2(k.astype(np.float32))).astype(np.float32)


scale = np.float32(1.0 / np.sqrt(D))
S = (Q @ K.T).astype(np.float32) * scale
m = S.max(axis=1, keepdims=True)
e = mu_exp((S - m).astype(np.float32))
P = (e / e.sum(axis=1, keepdims=True)).astype(np.float32)
O = (P @ V).astype(np.float32)


def emit(f, name, arr):
    flat = arr.flatten()
    f.write(f"__global float {name}[{flat.size}] = {{\n")
    f.write(",\n".join(f"{x:.9e}f" for x in flat))
    f.write("\n};\n")


with open("data", "w") as f:
    f.write("// generated by gen_data.py - do not edit\n")
    f.write(f"#define VERIFY_COUNT {SEQ * D}\n")
    f.write(f"static const uint32_t SEQ = {SEQ};\n")
    f.write(f"static const uint32_t HEAD_DIM = {D};\n")
    emit(f, "q_raw", Q)
    emit(f, "k_raw", K)
    emit(f, "v_raw", V)
    emit(f, "o_raw", np.zeros((SEQ, D), dtype=np.float32))
    emit(f, "gold_raw", O)
    f.write("__global float tls_guard[1024] = {0};\n")
print(f"wrote data: attention seq={SEQ} d={D}")
