#!/usr/bin/env python3
"""Gemma-2 RMSNorm (1+w): OUT[r,:] = x / sqrt(mean(x^2)+eps) * (1.0 + gamma)
(fp32, rows=16, cols=2304 = real Gemma-2-2b hidden_size).

Confirmed from HF transformers Gemma2RMSNorm.forward:
    output = x * rsqrt(x.pow(2).mean(-1) + eps)   # biased mean over hidden dim
    output = output * (1.0 + self.weight)          # weight stored ZERO-CENTERED
eps = config.rms_norm_eps = 1e-6. Weight is generated zero-centered (mean 0) to mirror the
real stored parameter, so the (1.0 + w) is load-bearing (vs test27 which multiplies by w directly).
"""
import numpy as np
R, Cc = 16, 2304
EPS = np.float32(1e-6)
rng = np.random.default_rng(40)
X = rng.standard_normal((R, Cc), dtype=np.float32)
# Zero-centered stored weight (Gemma inits to zeros; trained weights hover near 0).
gamma = (np.float32(0.1) * rng.standard_normal(Cc, dtype=np.float32)).astype(np.float32)
ms = (X.astype(np.float64) ** 2).mean(axis=1, keepdims=True)               # biased mean square
inv = (1.0 / np.sqrt(ms + EPS)).astype(np.float64)
gold = (X.astype(np.float64) * inv * (1.0 + gamma.astype(np.float64))).astype(np.float32)

def emit(f, name, arr):
    flat = arr.flatten()
    f.write(f"__global float {name}[{flat.size}] = {{\n")
    f.write(",\n".join(f"{x:.9e}f" for x in flat)); f.write("\n};\n")
with open("data", "w") as f:
    f.write("// generated by gen_data.py - do not edit\n")
    f.write(f"#define VERIFY_COUNT {R*Cc}\n")
    f.write(f"static const uint32_t ROWS = {R};\nstatic const uint32_t COLS = {Cc};\n")
    emit(f, "x_raw", X); emit(f, "gamma_raw", gamma)
    emit(f, "out_raw", np.zeros((R, Cc), np.float32)); emit(f, "gold_raw", gold)
    f.write("__global float tls_guard[1024] = {0};\n")
print(f"wrote data: Gemma RMSNorm(1+w) {R}x{Cc}")
