#!/usr/bin/env python3
"""Tall-skinny matmul: C[M,N] = A[M,K] @ B[K,N], fp32, M=8, K=256, N=768.

Real op: tiny_llama decode 8x2048, rdt 1x256@256x2048 (small batch / few rows). Only M=8 output
rows => most of the 128 threads idle unless work is mapped over N; an underutilization study.
"""
import numpy as np

M, N, K = 8, 768, 256
rng = np.random.default_rng(713)
A = rng.standard_normal((M, K), dtype=np.float32)
B = rng.standard_normal((K, N), dtype=np.float32)

gold = np.zeros((M, N), dtype=np.float32)
for k in range(K):
    gold += A[:, k : k + 1] * B[k : k + 1, :]


def emit(f, name, arr):
    flat = arr.flatten()
    f.write(f"__global float {name}[{flat.size}] = {{\n")
    f.write(",\n".join(f"{x:.9e}f" for x in flat))
    f.write("\n};\n")


with open("data", "w") as f:
    f.write("// generated by gen_data.py - do not edit\n")
    f.write(f"#define VERIFY_COUNT {M * N}\n")
    f.write(f"static const uint32_t M = {M};\n")
    f.write(f"static const uint32_t N = {N};\n")
    f.write(f"static const uint32_t K = {K};\n")
    emit(f, "A_raw", A)
    emit(f, "B_raw", B)
    emit(f, "C_raw", np.zeros((M, N), dtype=np.float32))
    emit(f, "gold_raw", gold)
    f.write("__global float tls_guard[1024] = {0};\n")
print(f"wrote data: tall-skinny matmul M={M} N={N} K={K}")
