#!/usr/bin/env python3
"""RoPE (rotary position embedding), HF Llama / GPT-NeoX rotate_half convention.

TinyLlama attention applies RoPE to Q and K before the score matmul. For a per-(position,head)
vector x of head_dim d and rotary base theta=10000:
    inv_freq[i] = theta^(-2i/d),  i in [0, d/2)
    angle[pos,i] = pos * inv_freq[i]
    cos/sin caches are duplicated across the two halves: c[pos,j]=cos(angle[pos, j mod d/2]).
    rotate_half(x)[j] = -x[j+d/2]  (j < d/2)  |  x[j-d/2]  (j >= d/2)
    out = x*cos + rotate_half(x)*sin

We flatten to ROWS=seq*n_heads rows of COLS=head_dim (cos/sin repeated per head so each row is
self-contained -- the kernel needs no positional arithmetic). fp32; matches HF RotaryEmbedding.
"""
import numpy as np

SEQ, N_HEADS, HEAD_DIM, THETA = 32, 4, 512, 10000.0
ROWS, COLS = SEQ * N_HEADS, HEAD_DIM
rng = np.random.default_rng(26)

half = HEAD_DIM // 2
inv_freq = (THETA ** (-(np.arange(0, half, dtype=np.float64) * 2.0 / HEAD_DIM))).astype(np.float64)
pos = np.arange(SEQ, dtype=np.float64)[:, None]            # [SEQ,1]
ang = pos * inv_freq[None, :]                              # [SEQ, half]
cos_h = np.cos(ang); sin_h = np.sin(ang)                   # [SEQ, half]
cos_cache = np.concatenate([cos_h, cos_h], axis=1)         # [SEQ, HEAD_DIM]  (duplicated)
sin_cache = np.concatenate([sin_h, sin_h], axis=1)

X = rng.standard_normal((SEQ, N_HEADS, HEAD_DIM)).astype(np.float64)
def rotate_half(x):
    x1, x2 = x[..., :half], x[..., half:]
    return np.concatenate([-x2, x1], axis=-1)
gold = (X * cos_cache[:, None, :] + rotate_half(X) * sin_cache[:, None, :])   # [SEQ,N_HEADS,HEAD_DIM]

# flatten to [ROWS, COLS]; cos/sin repeated per head so each row self-contains its rotation
X_f    = X.reshape(ROWS, COLS).astype(np.float32)
gold_f = gold.reshape(ROWS, COLS).astype(np.float32)
cos_f  = np.repeat(cos_cache, N_HEADS, axis=0).astype(np.float32)  # [SEQ*N_HEADS, COLS]
sin_f  = np.repeat(sin_cache, N_HEADS, axis=0).astype(np.float32)

def emit(f, name, arr):
    flat = arr.flatten()
    f.write(f"__global float {name}[{flat.size}] = {{\n")
    f.write(",\n".join(f"{x:.9e}f" for x in flat)); f.write("\n};\n")

with open("data", "w") as f:
    f.write("// generated by gen_data.py - do not edit\n")
    f.write(f"#define VERIFY_COUNT {ROWS * COLS}\n")
    f.write(f"static const uint32_t ROWS = {ROWS};\n")
    f.write(f"static const uint32_t COLS = {COLS};\n")
    f.write(f"static const uint32_t HALF = {half};\n")
    emit(f, "x_raw", X_f); emit(f, "cos_raw", cos_f); emit(f, "sin_raw", sin_f)
    emit(f, "out_raw", np.zeros((ROWS, COLS), np.float32)); emit(f, "gold_raw", gold_f)
    f.write("__global float tls_guard[1024] = {0};\n")
print(f"wrote data: RoPE(hidden2048) seq={SEQ} heads={N_HEADS} d={HEAD_DIM} -> {ROWS}x{COLS}")
