#!/usr/bin/env python3
"""Conv2d patch-embedding tile (SigLIP/DINO): IN[C,H,W] * W[OC,C,16,16] stride 16 -> OUT[OC,4,4].

Real op: openvla 1x3x64x64 * 192x3x16x16 (model2MLIR). One tile: OC=16, H=W=64.
"""
import numpy as np

C, H, W = 3, 64, 64
OC, KH, KW, S = 16, 16, 16, 16
OH, OW = H // S, W // S

rng = np.random.default_rng(7)
inp = rng.standard_normal((C, H, W), dtype=np.float32)
wgt = rng.standard_normal((OC, C, KH, KW), dtype=np.float32) * 0.1

gold = np.zeros((OC, OH, OW), dtype=np.float32)
for oc in range(OC):
    for oh in range(OH):
        for ow in range(OW):
            acc = np.float32(0)
            for c in range(C):
                for kh in range(KH):
                    for kw in range(KW):
                        acc += inp[c, oh * S + kh, ow * S + kw] * wgt[oc, c, kh, kw]
            gold[oc, oh, ow] = acc


def emit(f, name, arr):
    flat = arr.flatten()
    f.write(f"__global float {name}[{flat.size}] = {{\n")
    f.write(",\n".join(f"{x:.9e}f" for x in flat))
    f.write("\n};\n")


with open("data", "w") as f:
    f.write("// generated by gen_data.py - do not edit\n")
    f.write(f"#define VERIFY_COUNT {OC * OH * OW}\n")
    f.write(f"static const uint32_t C = {C}, H = {H}, W = {W};\n")
    f.write(f"static const uint32_t OC = {OC}, KH = {KH}, KW = {KW}, STRIDE = {S};\n")
    f.write(f"static const uint32_t OH = {OH}, OW = {OW};\n")
    emit(f, "in_raw", inp)
    emit(f, "w_raw", wgt)
    emit(f, "out_raw", np.zeros((OC, OH, OW), dtype=np.float32))
    emit(f, "gold_raw", gold)
    f.write("__global float tls_guard[1024] = {0};\n")
print(f"wrote data: conv {C}x{H}x{W} * {OC}x{C}x{KH}x{KW} s{S} -> {OC}x{OH}x{OW}")
