#!/usr/bin/env python3
"""Large-K matmul: C[M,N] = A[M,K] @ B[K,N], fp32, M=N=64, K=384.

Real op: smolvla dominant 1024x768@768x768 (x48). K=384 => A[64x384]+B[384x64] = 192 KB > 128 KiB
SMEM, so a tiled kernel must STREAM K (load K-chunk to SMEM, accumulate, advance). Sequential fp32
float64 golden. (K=768 hit a cyclotron functional issue on the 49K-elem globals - filed separately; K=384 still forces streaming.)
"""
import numpy as np

M, N, K = 64, 64, 384
rng = np.random.default_rng(710)
A = rng.standard_normal((M, K), dtype=np.float32)
B = rng.standard_normal((K, N), dtype=np.float32)

# float64 reference (true answer); the device's fp32 fma is closer to this than an fp32-sequential
# numpy sum (mul+add, 2 roundings/step) would be — at K=768 that mismatch exceeds 1e-3. tol covers
# device-fma vs true (~K*eps ~ 5e-5 rel).
gold = (A.astype(np.float64) @ B.astype(np.float64)).astype(np.float32)


def emit(f, name, arr):
    flat = arr.flatten()
    f.write(f"__global float {name}[{flat.size}] = {{\n")
    f.write(",\n".join(f"{x:.9e}f" for x in flat))
    f.write("\n};\n")


with open("data", "w") as f:
    f.write("// generated by gen_data.py - do not edit\n")
    f.write(f"#define VERIFY_COUNT {M * N}\n")
    f.write(f"static const uint32_t M = {M};\n")
    f.write(f"static const uint32_t N = {N};\n")
    f.write(f"static const uint32_t K = {K};\n")
    emit(f, "A_raw", A)
    emit(f, "B_raw", B)
    emit(f, "C_raw", np.zeros((M, N), dtype=np.float32))
    emit(f, "gold_raw", gold)
    f.write("__global float tls_guard[1024] = {0};\n")
print(f"wrote data: large-K matmul M={M} N={N} K={K}")
