#!/usr/bin/env python3
"""RMSNorm: OUT[r,:] = x / sqrt(mean(x^2)+eps) * gamma  (fp32, rows=64, cols=512=hidden).

TinyLlama/Llama uses RMSNorm (NO mean subtraction, NO beta), unlike LayerNorm. mean(x^2) is
over the hidden dim (biased). eps=1e-5. Matches HF LlamaRMSNorm (which upcasts to fp32).
"""
import numpy as np
R, Cc = 64, 512
EPS = np.float32(1e-5)
rng = np.random.default_rng(27)
X = rng.standard_normal((R, Cc), dtype=np.float32)
gamma = (np.float32(1.0) + np.float32(0.1) * rng.standard_normal(Cc, dtype=np.float32)).astype(np.float32)
ms = (X.astype(np.float64) ** 2).mean(axis=1, keepdims=True)               # mean square (fp64 accum)
inv = (1.0 / np.sqrt(ms + EPS)).astype(np.float64)
gold = (X.astype(np.float64) * inv * gamma.astype(np.float64)).astype(np.float32)

def emit(f, name, arr):
    flat = arr.flatten()
    f.write(f"__global float {name}[{flat.size}] = {{\n")
    f.write(",\n".join(f"{x:.9e}f" for x in flat)); f.write("\n};\n")
with open("data", "w") as f:
    f.write("// generated by gen_data.py - do not edit\n")
    f.write(f"#define VERIFY_COUNT {R*Cc}\n")
    f.write(f"static const uint32_t ROWS = {R};\nstatic const uint32_t COLS = {Cc};\n")
    emit(f, "x_raw", X); emit(f, "gamma_raw", gamma)
    emit(f, "out_raw", np.zeros((R, Cc), np.float32)); emit(f, "gold_raw", gold)
    f.write("__global float tls_guard[1024] = {0};\n")
print(f"wrote data: RMSNorm {R}x{Cc}")
