#!/usr/bin/env python3
"""FUSED QKV-proj(MX) + RoPE(SIMT) problem data.

Golden = RoPE( bf16( MX_matmul(X, W) ), cos, sin ), computed with the HARDWARE matmul
semantics (autocomp mx_golden: 16-deep accumulator, acc_e/acc_m schedule, e8m0 per-32-K
scales) then HF-Llama rotate_half in fp32 on the bf16 matmul output, truncated back to bf16
(the kernel truncates identically -> bit-exact). Shape: M=16 (seq) x N=64 (head_dim, 1 head)
x K=64 (hidden). cos/sin duplicated across the two halves.
"""
import pathlib, subprocess
import numpy as np

M, N, K = 64, 64, 64
HALF = N // 2
THETA = 10000.0
GROUP = 32
HERE = pathlib.Path(__file__).resolve().parent
MX_GOLDEN = pathlib.Path("/scratch/agustin/projects/autocomp/scripts/muon/mx_golden/mx_golden")
rng = np.random.default_rng(33)


def rand_fp8(n):  # fp8 e4m3 codes with |value| <= 1 (exp field <= bias)
    exp = rng.integers(0, 8, n, np.uint8); mant = rng.integers(0, 8, n, np.uint8)
    sign = rng.integers(0, 2, n, np.uint8)
    return ((sign << 7) | (exp << 3) | mant).astype(np.uint8)


A = rand_fp8(M * K).reshape(M, K)                 # X
B = rand_fp8(K * N).reshape(K, N)                 # W
GK = K // GROUP
SA = rng.integers(0x7B, 0x83, (GK, M), np.uint8)  # e8m0 near 1.0
SB = rng.integers(0x7B, 0x83, (GK, N), np.uint8)

tmp = HERE / "_gen"; tmp.mkdir(exist_ok=True)
for nm, arr in [("A", A), ("B", B), ("SA", SA), ("SB", SB)]:
    (tmp / f"{nm}.bin").write_bytes(arr.tobytes())
subprocess.run([str(MX_GOLDEN), str(M), str(N), str(K), str(tmp/"A.bin"), str(tmp/"B.bin"),
                str(tmp/"SA.bin"), str(tmp/"SB.bin"), str(tmp/"C.bin"), "0"],
               check=True, env={"PATH": "/usr/bin:/bin"})              # fullout bf16
C_bf16 = np.frombuffer((tmp/"C.bin").read_bytes(), "<u2").reshape(M, N)  # hardware matmul, bf16

# RoPE cos/sin cache, duplicated across halves
inv = (THETA ** (-(np.arange(HALF) * 2.0 / N))).astype(np.float64)
ang = np.arange(M)[:, None] * inv[None, :]
cos = np.concatenate([np.cos(ang), np.cos(ang)], 1)   # [M,N]
sin = np.concatenate([np.sin(ang), np.sin(ang)], 1)

def bf16_to_f(u16): return (u16.astype(np.uint32) << 16).view(np.float32)
def f_to_bf16(f):   return (f.astype(np.float32).view(np.uint32) >> 16).astype(np.uint16)  # truncate

Cf = bf16_to_f(C_bf16)                                  # bf16 matmul output as fp32
rot = np.concatenate([-Cf[:, HALF:], Cf[:, :HALF]], 1)  # rotate_half
gold = f_to_bf16(Cf * cos + rot * sin)                  # [M,N] bf16
cos_f = cos.astype(np.float32); sin_f = sin.astype(np.float32)


def emit(f, ctype, name, dims, arr):
    w = 2 if ctype == "uint8_t" else (4 if ctype == "uint16_t" else 8)
    f.write(f"static const {ctype} {name}{dims} = {{\n")
    rows = ["    " + ", ".join(f"0x{v:0{w}x}" for v in row) for row in arr]
    f.write(",\n".join(rows)); f.write("\n};\n")


with open(HERE / "data", "w") as f:
    f.write("// @generated by gen_data.py -- fused QKV(MX)+RoPE(SIMT)\n#include <stdint.h>\n")
    f.write(f"#define MATMUL_M {M}\n#define MATMUL_N {N}\n#define MATMUL_K {K}\n")
    f.write(f"#define MATMUL_GK {GK}\n#define MATMUL_GN {N//GROUP}\n")
    f.write(f"#define VERIFY_COUNT {M*N}\n")
    emit(f, "uint8_t",  "A_in",         "[MATMUL_M][MATMUL_K]", A)
    emit(f, "uint8_t",  "B_in",         "[MATMUL_K][MATMUL_N]", B)
    emit(f, "uint8_t",  "A_scales_row", "[MATMUL_GK][MATMUL_M]", SA)
    emit(f, "uint8_t",  "B_scales_col", "[MATMUL_GK][MATMUL_N]", SB)
    # cos/sin as fp32 bit patterns
    emit(f, "uint32_t", "cos_bits", "[MATMUL_M][MATMUL_N]", cos_f.view(np.uint32).reshape(M, N))
    emit(f, "uint32_t", "sin_bits", "[MATMUL_M][MATMUL_N]", sin_f.view(np.uint32).reshape(M, N))
    emit(f, "uint16_t", "C_out",  "[MATMUL_M][MATMUL_N]", np.zeros((M, N), np.uint16))
    emit(f, "uint16_t", "gold_raw_2d", "[MATMUL_M][MATMUL_N]", gold)
    f.write("static const float* cos_raw = (const float*)&cos_bits[0][0];\n")
    f.write("static const float* sin_raw = (const float*)&sin_bits[0][0];\n")
    f.write("static const uint16_t* C_raw = &C_out[0][0];\n")
    f.write("static const uint16_t* gold_raw = &gold_raw_2d[0][0];\n")
    f.write("__global float tls_guard[1024] = {0};\n")
print(f"wrote data: fused QKV+RoPE M={M} N={N} K={K}")
