#!/usr/bin/env python3
"""Generate `data` for muon problem 20: MX-Gemmini FP8 matmul on the WHOLE Radiance
config (Muon SIMT cores driving the MX matrix accelerator over MMIO).

  C[M,N] (bf16) = A[M,K] (fp8 e4m3) @ B[K,N] (fp8 e4m3), with per-32-K-block e8m0 scales.

The golden is produced by `scripts/muon/mx_golden`, a host reference implementing the
HARDWARE accumulation semantics (16-deep systolic accumulator with the acc_e/acc_m
precision schedule, one e8m0 scaling per 32-element K group). It is verified bit-exact
against REAL spike libgemmini.

Do NOT use radiance-kernels' `fp8_matmul_model.py` golden here: that is an *idealized*
model which bf16-rounds after every single k, and disagrees with the hardware on ~90% of
elements (mean rel err ~2.5%). Real spike disagrees with it exactly as much as we do.
"""
import pathlib
import subprocess
import struct
import numpy as np

M, N, K = 128, 128, 512
GK = K // 32
MX_GOLDEN = pathlib.Path(__file__).resolve().parents[3] / "scripts/muon/mx_golden/mx_golden"

rng = np.random.default_rng(20260709)


def rand_fp8(n):
    """Random fp8 e4m3 codes with |value| <= 1.

    Magnitudes matter: the accelerator accumulates through a 16-deep systolic array whose
    first columns carry only e4m4 precision (max normal ~448). With unrestricted fp8
    operands (|a| up to 448) a 64-deep dot product saturates and essentially every golden
    element comes out +/-inf -- a golden that any broken kernel matches. Capping the
    exponent field at the bias (e <= 7 => |a| <= 1) keeps the partial sums well inside the
    block accumulator's range.
    """
    exp = rng.integers(0, 8, size=n, dtype=np.uint8)  # e <= 7 (bias 7) => |value| <= 1
    mant = rng.integers(0, 8, size=n, dtype=np.uint8)
    sign = rng.integers(0, 2, size=n, dtype=np.uint8)
    return ((sign << 7) | (exp << 3) | mant).astype(np.uint8)

A = rand_fp8(M * K).reshape(M, K)
B = rand_fp8(K * N).reshape(K, N)
# e8m0 scale codes near 1.0 (0x7f == 2^0)
A_scales = rng.integers(0x7b, 0x83, size=(GK, M), dtype=np.uint8)
B_scales = rng.integers(0x7b, 0x83, size=(GK, N), dtype=np.uint8)

tmp = pathlib.Path("_mxgen")
tmp.mkdir(exist_ok=True)
(tmp / "A.bin").write_bytes(A.tobytes())
(tmp / "B.bin").write_bytes(B.tobytes())
(tmp / "SA.bin").write_bytes(A_scales.tobytes())
(tmp / "SB.bin").write_bytes(B_scales.tobytes())

if not MX_GOLDEN.exists():
    raise SystemExit(f"build the golden first:  g++ -O2 -std=c++17 mx_golden.cpp -o {MX_GOLDEN}")
subprocess.run(
    [str(MX_GOLDEN), str(M), str(N), str(K), str(tmp / "A.bin"), str(tmp / "B.bin"),
     str(tmp / "SA.bin"), str(tmp / "SB.bin"), str(tmp / "C.bin"), "0"],
    check=True,
)
gold = np.frombuffer((tmp / "C.bin").read_bytes(), dtype="<u2").reshape(M, N)


def emit_u8_2d(f, name, arr, dims):
    f.write(f"static const uint8_t {name}{dims} = {{\n")
    rows = ["    " + ",".join(f"0x{v:02x}" for v in row) for row in arr]
    f.write(",\n".join(rows))
    f.write("\n};\n")


with open("data", "w") as f:
    f.write("// generated by gen_data.py - do not edit\n")
    f.write(f"#define MATMUL_M {M}\n#define MATMUL_N {N}\n#define MATMUL_K {K}\n")
    f.write(f"#define MATMUL_GK {GK}\n#define MATMUL_GN {N // 32}\n")
    f.write(f"#define VERIFY_COUNT {M * N}\n")
    emit_u8_2d(f, "A_in", A, "[MATMUL_M][MATMUL_K]")
    emit_u8_2d(f, "B_in", B, "[MATMUL_K][MATMUL_N]")
    emit_u8_2d(f, "A_scales_row", A_scales, "[MATMUL_GK][MATMUL_M]")
    emit_u8_2d(f, "B_scales_col", B_scales, "[MATMUL_GK][MATMUL_N]")
    # fp8 path never consults the LUTs, but mxgemm_lib.hpp references them unconditionally
    f.write("static const uint32_t A_lut[64][3] = {0};\n")
    f.write("static const uint32_t B_lut[64][3] = {0};\n")
    f.write("static const uint32_t C_lut[64][3] = {0};\n")
    # bf16 golden, and the device-written output buffer
    f.write(f"static const uint16_t gold_raw[{M * N}] = {{\n")
    f.write(",\n".join(",".join(f"0x{v:04x}" for v in row) for row in gold))
    f.write("\n};\n")
    f.write(f"__global uint16_t C_raw[{M * N}] = {{0}};\n")
    f.write("__global float tls_guard[1024] = {0};\n")

print(f"wrote data: M={M} N={N} K={K}  (golden from mx_golden, spike-bit-exact)")
