#!/usr/bin/env python3
"""Gemma-2 decoder-layer NORM/RESIDUAL wiring golden (fp32, R=8, D=2304).

Replicates the EXACT ordering from HF transformers Gemma2DecoderLayer.forward (confirmed by
reading modeling_gemma2.py). Norms are Gemma2RMSNorm: rms(x)*(1.0+weight), eps=1e-6, weight
zero-centered. self_attn and mlp are stubbed as deterministic per-channel scales (wa, wm) --
the object under test is the norm/residual TOPOLOGY, not the sublayer math (covered elsewhere).
"""
import numpy as np
R, D = 8, 2304
EPS = np.float32(1e-6)
rng = np.random.default_rng(42)

def rmsnorm_1w(x, w):
    ms = (x.astype(np.float64) ** 2).mean(axis=-1, keepdims=True)
    inv = 1.0 / np.sqrt(ms + EPS)
    return (x.astype(np.float64) * inv * (1.0 + w.astype(np.float64)))

X    = rng.standard_normal((R, D), dtype=np.float32)
w_in = (np.float32(0.1) * rng.standard_normal(D, dtype=np.float32)).astype(np.float32)
w_pa = (np.float32(0.1) * rng.standard_normal(D, dtype=np.float32)).astype(np.float32)
w_pf = (np.float32(0.1) * rng.standard_normal(D, dtype=np.float32)).astype(np.float32)
w_pff= (np.float32(0.1) * rng.standard_normal(D, dtype=np.float32)).astype(np.float32)
wa   = (np.float32(1.0) + np.float32(0.1) * rng.standard_normal(D, dtype=np.float32)).astype(np.float32)
wm   = (np.float32(1.0) + np.float32(0.1) * rng.standard_normal(D, dtype=np.float32)).astype(np.float32)

# --- exact Gemma2DecoderLayer wiring (all math in fp64, cast final to fp32) ---
h = X.astype(np.float64)
residual = h
h = rmsnorm_1w(X, w_in)                       # NORM 1  input_layernorm
h = h * wa.astype(np.float64)                 # self_attn (stub)
h = rmsnorm_1w(h.astype(np.float32), w_pa)    # NORM 2  post_attention_layernorm
h = residual + h                              # RESIDUAL 1
residual = h
h = rmsnorm_1w(h.astype(np.float32), w_pf)    # NORM 3  pre_feedforward_layernorm
h = h * wm.astype(np.float64)                 # mlp (stub)
h = rmsnorm_1w(h.astype(np.float32), w_pff)   # NORM 4  post_feedforward_layernorm
h = residual + h                              # RESIDUAL 2
gold = h.astype(np.float32)

def emit(f, name, arr):
    flat = arr.flatten()
    f.write(f"__global float {name}[{flat.size}] = {{\n")
    f.write(",\n".join(f"{x:.9e}f" for x in flat)); f.write("\n};\n")
with open("data", "w") as f:
    f.write("// generated by gen_data.py - do not edit\n")
    f.write(f"#define VERIFY_COUNT {R*D}\n")
    f.write(f"static const uint32_t ROWS = {R};\nstatic const uint32_t COLS = {D};\n")
    emit(f, "x_raw", X)
    emit(f, "w_in_raw", w_in); emit(f, "w_pa_raw", w_pa)
    emit(f, "w_pf_raw", w_pf); emit(f, "w_pff_raw", w_pff)
    emit(f, "wa_raw", wa); emit(f, "wm_raw", wm)
    emit(f, "tmp_raw", np.zeros((R, D), np.float32))
    emit(f, "out_raw", np.zeros((R, D), np.float32)); emit(f, "gold_raw", gold)
    f.write("__global float tls_guard[1024] = {0};\n")
print(f"wrote data: Gemma 4-norm wiring R={R} D={D}")
