#!/usr/bin/env python3
"""Row softmax tile: OUT[r, :] = softmax(IN[r, :]) (fp32, rows=64, cols=67).

Real op: rdt attention logits 1x32x67.
"""
import numpy as np

R, Cc = 64, 67
rng = np.random.default_rng(33)
X = rng.standard_normal((R, Cc), dtype=np.float32)


def mu_exp(x):
    x = np.float32(x)
    log2e = np.float32(1.4426950408889634)
    ln2 = np.float32(0.6931471805599453)
    t = x * log2e
    k = np.where(t >= 0, t + np.float32(0.5), t - np.float32(0.5)).astype(np.int32)
    r = x - k.astype(np.float32) * ln2
    p = np.float32(1.0) + r * (np.float32(1.0) + r * (np.float32(0.5) + r * (
        np.float32(0.16666667) + r * (np.float32(0.041666668) + r * np.float32(0.008333334)))))
    return (p * np.exp2(k.astype(np.float32))).astype(np.float32)


m = X.max(axis=1, keepdims=True)
e = mu_exp((X - m).astype(np.float32))
gold = (e / e.sum(axis=1, keepdims=True)).astype(np.float32)


def emit(f, name, arr):
    flat = arr.flatten()
    f.write(f"__global float {name}[{flat.size}] = {{\n")
    f.write(",\n".join(f"{x:.9e}f" for x in flat))
    f.write("\n};\n")


with open("data", "w") as f:
    f.write("// generated by gen_data.py - do not edit\n")
    f.write(f"#define VERIFY_COUNT {R * Cc}\n")
    f.write(f"static const uint32_t ROWS = {R};\n")
    f.write(f"static const uint32_t COLS = {Cc};\n")
    emit(f, "x_raw", X)
    emit(f, "out_raw", np.zeros((R, Cc), dtype=np.float32))
    emit(f, "gold_raw", gold)
    f.write("__global float tls_guard[1024] = {0};\n")
print(f"wrote data: softmax {R}x{Cc}")
